"""initial schema

Revision ID: 3196a0cde329
Revises: 
Create Date: 2026-09-13 19:22:36.629322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3196a0cde329'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('attribute_type', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('varieties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subcriteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('technical_range', sa.String(length=191), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criterion_id', 'name')
    )
    with op.batch_alter_table('subcriteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcriteria_criterion_id'), ['criterion_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('variety_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('source_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variety_id', 'criterion_id')
    )
    with op.batch_alter_table('variety_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variety_scores_criterion_id'), ['criterion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_variety_scores_variety_id'), ['variety_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=191), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('criteria_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(length=191), nullable=False),
    sa.Column('mapped_score', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('mapping_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['recommendation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'criterion_id')
    )
    op.create_table('recommendation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('rank_no', sa.Integer(), nullable=False),
    sa.Column('distance_positive', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('distance_negative', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.Column('preference_score', sa.Numeric(precision=20, scale=12), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['recommendation_sessions.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'variety_id')
    )
    op.create_table('topsis_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('decision_matrix', sa.JSON(), nullable=False),
    sa.Column('normalization_matrix', sa.JSON(), nullable=False),
    sa.Column('weighted_matrix', sa.JSON(), nullable=False),
    sa.Column('positive_ideal', sa.JSON(), nullable=False),
    sa.Column('negative_ideal', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['recommendation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topsis_calculations')
    op.drop_table('recommendation_results')
    op.drop_table('recommendation_inputs')
    with op.batch_alter_table('recommendation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_sessions_created_at'))

    op.drop_table('recommendation_sessions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('variety_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variety_scores_variety_id'))
        batch_op.drop_index(batch_op.f('ix_variety_scores_criterion_id'))

    op.drop_table('variety_scores')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subcriteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcriteria_criterion_id'))

    op.drop_table('subcriteria')
    op.drop_table('varieties')
    op.drop_table('roles')
    op.drop_table('criteria')
    # ### end Alembic commands ###
